dataset: IgG-RL
gt_dir: /scratch/gpfs/ZHONGE/mj7341/data/cryobench/IgG-RL/vols/128_org/

pred_models:
  - name: CryoHype (No noise)
    path: /scratch/gpfs/ZHONGE/mj7341/research/01_generalizable-cryoem/results/IgG-RL/proj/ours/crop_5views/vols_Apix3
    thresholds_file: /path/to/CryoHype_no_noise_predicted_levels.txt
  - name: CryoDRGN (No noise)
    path: /scratch/gpfs/ZHONGE/mj7341/research/01_generalizable-cryoem/metrics/per_image_fsc/proj/IgG-RL/cryodrgn_20ep/vols
    thresholds_file: /path/to/CryoDRGN_no_noise_predicted_levels.txt
  - name: CryoHype (SNR 0.01)
    path: /scratch/gpfs/ZHONGE/jg1427/results/IgG-RL/noisy_crop/vols
    thresholds_file: /path/to/CryoHype_snr001_predicted_levels.txt
  - name: CryoDRGN (SNR 0.01)
    path: /scratch/gpfs/ZHONGE/mj7341/research/01_generalizable-cryoem/metrics/per_image_fsc/snr001/IgG-RL/cryodrgn/cryodrgn_20ep/vols
    thresholds_file: /path/to/CryoDRGN_snr001_predicted_levels.txt

mask: /scratch/gpfs/ZHONGE/mj7341/data/cryobench/IgG-RL/init_mask/mask.mrc
grid_size: 128
voxel_size: 4.5
output_dir: ./results/IgG-RL_levels
